doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                driver: 'pdo_mysql'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

                url: '%env(resolve:DATABASE_URL)%'
            ods_legacy:
                # configure these for your database server
                driver: 'pdo_mysql'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

                url: '%env(resolve:DATABASE_ODS_LEGACY_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            datetime_functions:
                YEAR: DoctrineExtensions\Query\Mysql\Year
                MONTH: DoctrineExtensions\Query\Mysql\Month
                DAY: DoctrineExtensions\Query\Mysql\Day
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                DAYOFYEAR: DoctrineExtensions\Query\Mysql\DayOfYear
                MAKEDATE: DoctrineExtensions\Query\Mysql\MakeDate
            numeric_functions:
                rand: DoctrineExtensions\Query\Mysql\Rand
            string_functions:
                regexp: DoctrineExtensions\Query\Mysql\Regexp
                group_concat: DoctrineExtensions\Query\Mysql\GroupConcat
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
