services:

  db:
    image: mariadb:11.3
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - "mbnet"
    ports:
      - "127.0.0.1:3306:3306"
    expose:
      - 3306

  web:
    build:
      context: .
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        APP_ENV: ${APP_ENV}
        APP_SECRET: ${APP_SECRET}
        DEFAULT_URI: ${DEFAULT_URI}
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - "mbnet"

networks:
 mbnet:
