accueil:
    path: /
    controller: App\Controller\PagesController::index

apropos:
    path: /apropos
    controller: App\Controller\PagesController::defaultPageRenderer

actualites:
    path: /actualites
    controller: App\Controller\PagesController::defaultPageRenderer

actu:
    path: /actualites/actu
    controller: App\Controller\PagesController::defaultPageRenderer

evenements:
    path: /evenements
    controller: App\Controller\PagesController::defaultPageRenderer

evenement:
    path: /evenements/evenement
    controller: App\Controller\PagesController::defaultPageRenderer

especes:
    path: /especes
    controller: App\Controller\PagesController::defaultPageRenderer

participer:
    path: /participer
    controller: App\Controller\PagesController::defaultPageRenderer

stations:
    path: /participer/stations
    controller: App\Controller\PagesController::defaultPageRenderer

station-page:
    path: /participer/stations/station-page
    controller: App\Controller\PagesController::defaultPageRenderer

resultats:
    path: /resultats
    controller: App\Controller\PagesController::defaultPageRenderer

outils-ressources:
    path: /outils-ressources
    controller: App\Controller\PagesController::defaultPageRenderer

relais:
    path: /relais
    controller: App\Controller\PagesController::defaultPageRenderer
