name: OBS
run-name: OBS
on:
  push:
    branches:
      - docker-test
jobs:
  Deploy-Docker-Compose:
    runs-on: [self-hosted, linux, x64]
    environment: 'obs-test'
    env:
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASSWORD: ${{ vars.DB_PASSWORD }}
      DB_ROOT_PASSWORD: ${{ vars.DB_ROOT_PASSWORD }}
      APP_ENV: ${{ vars.APP_ENV }}
      APP_SECRET: ${{ vars.APP_SECRET }}
      DEFAULT_URI: ${{ vars.DEFAULT_URI }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'Funloi2/obs-saisons.fr'
          ref: 'docker-test'
      - name: down
        run: sudo -E docker-compose down
      - name: clear cache
        run: sudo -E docker system prune -af
      - name: Build
        run: sudo -E docker-compose build
      - name: Up file
        run: sudo -E docker-compose up -d


