name: OBS
run-name: OBS
on:
  push:
    branches:
      - graphiqueV2
jobs:
  Deploy-Docker-Compose:
    runs-on: [self-hosted, linux, x64]
    environment: 'obs-test'
    env:
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASSWORD: ${{ vars.DB_PASSWORD }}
      DB_ROOT_PASSWORD: ${{ vars.DB_ROOT_PASSWORD }}
      APP_ENV: ${{ vars.APP_ENV }}
      APP_SECRET: ${{ vars.APP_SECRET }}
      DEFAULT_URI: ${{ vars.DEFAULT_URI }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'Funloi2/obs-saisons.fr'
          ref: 'docker-test'
      - name: down
        run: sudo -E docker-compose down
      - name: clear cache
        run: sudo -E docker system prune -af
      - name: Build
        run: sudo -E docker-compose build
      - name: Up file
        run: sudo -E docker-compose up -d

#      - name: Docker Compose Action
#        uses: smartlyio/docker-compose-action@latest
#        with:
#          composeFile: "docker-compose.yml" # Path to your docker-compose file
#          serviceName: "web" # The name of the service to use defined in the compose file
#          composeCommand: "up" # The main compose command to execute
#          composeArguments: "-d" # Option flags passed to the compose command
#          build: true # Explicitly build the service image before running
##          push: "on:push"
#          env:
#            DB_NAME=${{ secrets.DB_NAME }}
#            DB_USER=${{ secrets.DB_USER }}
#            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
#            APP_ENV=${{ secrets.APP_ENV }}
#            APP_SECRET=${{ secrets.APP_SECRET }}
#            DEFAULT_URI=${{ secrets.DEFAULT_URI }}

